// Code generated by "stringer -type ImageUsageFlagBits -output image_usage_flags_string.go"; DO NOT EDIT.

package vulkan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ImageUsageTransferSrcBit-1]
	_ = x[ImageUsageTransferDstBit-2]
	_ = x[ImageUsageSampledBit-4]
	_ = x[ImageUsageStorageBit-8]
	_ = x[ImageUsageColorAttachmentBit-16]
	_ = x[ImageUsageDepthStencilAttachmentBit-32]
	_ = x[ImageUsageTransientAttachmentBit-64]
	_ = x[ImageUsageInputAttachmentBit-128]
}

const (
	_ImageUsageFlagBits_name_0 = "ImageUsageTransferSrcBitImageUsageTransferDstBit"
	_ImageUsageFlagBits_name_1 = "ImageUsageSampledBit"
	_ImageUsageFlagBits_name_2 = "ImageUsageStorageBit"
	_ImageUsageFlagBits_name_3 = "ImageUsageColorAttachmentBit"
	_ImageUsageFlagBits_name_4 = "ImageUsageDepthStencilAttachmentBit"
	_ImageUsageFlagBits_name_5 = "ImageUsageTransientAttachmentBit"
	_ImageUsageFlagBits_name_6 = "ImageUsageInputAttachmentBit"
)

var (
	_ImageUsageFlagBits_index_0 = [...]uint8{0, 24, 48}
)

func (i ImageUsageFlagBits) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ImageUsageFlagBits_name_0[_ImageUsageFlagBits_index_0[i]:_ImageUsageFlagBits_index_0[i+1]]
	case i == 4:
		return _ImageUsageFlagBits_name_1
	case i == 8:
		return _ImageUsageFlagBits_name_2
	case i == 16:
		return _ImageUsageFlagBits_name_3
	case i == 32:
		return _ImageUsageFlagBits_name_4
	case i == 64:
		return _ImageUsageFlagBits_name_5
	case i == 128:
		return _ImageUsageFlagBits_name_6
	default:
		return "ImageUsageFlagBits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
