// Code generated by "stringer -type PresentMode -output present_mode_string.go"; DO NOT EDIT.

package vulkan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PresentModeImmediate-0]
	_ = x[PresentModeMailbox-1]
	_ = x[PresentModeFIFO-2]
	_ = x[PresentModeFIFORelaxed-3]
	_ = x[PresentModeSharedDemandRefresh-1000111000]
	_ = x[PresentModeSharedContinuousRefresh-1000111001]
}

const (
	_PresentMode_name_0 = "PresentModeImmediatePresentModeMailboxPresentModeFIFOPresentModeFIFORelaxed"
	_PresentMode_name_1 = "PresentModeSharedDemandRefreshPresentModeSharedContinuousRefresh"
)

var (
	_PresentMode_index_0 = [...]uint8{0, 20, 38, 53, 75}
	_PresentMode_index_1 = [...]uint8{0, 30, 64}
)

func (i PresentMode) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _PresentMode_name_0[_PresentMode_index_0[i]:_PresentMode_index_0[i+1]]
	case 1000111000 <= i && i <= 1000111001:
		i -= 1000111000
		return _PresentMode_name_1[_PresentMode_index_1[i]:_PresentMode_index_1[i+1]]
	default:
		return "PresentMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
