// Code generated by "stringer -type=StructureType -output=structure_type_string.go"; DO NOT EDIT.

package vulkan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StructureTypeApplicationInfo-0]
	_ = x[StructureTypeInstanceCreateInfo-1]
	_ = x[StructureTypeDeviceQueueCreateInfo-2]
	_ = x[StructureTypeDeviceCreateInfo-3]
	_ = x[StructureTypeSubmitInfo-4]
	_ = x[StructureTypeMemoryAllocateInfo-5]
	_ = x[StructureTypeMappedMemoryRange-6]
	_ = x[StructureTypeBindSparseInfo-7]
	_ = x[StructureTypeFenceCreateInfo-8]
	_ = x[StructureTypeSemaphoreCreateInfo-9]
	_ = x[StructureTypeEventCreateInfo-10]
	_ = x[StructureTypeQueryPoolCreateInfo-11]
	_ = x[StructureTypeBufferCreateInfo-12]
	_ = x[StructureTypeBufferViewCreateInfo-13]
	_ = x[StructureTypeImageCreateInfo-14]
	_ = x[StructureTypeImageViewCreateInfo-15]
	_ = x[StructureTypeShaderModuleCreateInfo-16]
	_ = x[StructureTypePipelineCacheCreateInfo-17]
	_ = x[StructureTypePipelineShaderStageCreateInfo-18]
	_ = x[StructureTypePipelineVertexInputStateCreateInfo-19]
	_ = x[StructureTypePipelineInputAssemblyStateCreateInfo-20]
	_ = x[StructureTypePipelineTessellationStateCreateInfo-21]
	_ = x[StructureTypePipelineViewportStateCreateInfo-22]
	_ = x[StructureTypePipelineRasterizationStateCreateInfo-23]
	_ = x[StructureTypePipelineMultisampleStateCreateInfo-24]
	_ = x[StructureTypePipelineDepthStencilStateCreateInfo-25]
	_ = x[StructureTypePipelineColorBlendStateCreateInfo-26]
	_ = x[StructureTypePipelineDynamicStateCreateInfo-27]
	_ = x[StructureTypeGraphicsPipelineCreateInfo-28]
	_ = x[StructureTypeComputePipelineCreateInfo-29]
	_ = x[StructureTypePipelineLayoutCreateInfo-30]
	_ = x[StructureTypeSamplerCreateInfo-31]
	_ = x[StructureTypeDescriptorSetLayoutCreateInfo-32]
	_ = x[StructureTypeDescriptorPoolCreateInfo-33]
	_ = x[StructureTypeDescriptorSetAllocateInfo-34]
	_ = x[StructureTypeWriteDescriptorSet-35]
	_ = x[StructureTypeCopyDescriptorSet-36]
	_ = x[StructureTypeFramebufferCreateInfo-37]
	_ = x[StructureTypeRenderPassCreateInfo-38]
	_ = x[StructureTypeCommandPoolCreateInfo-39]
	_ = x[StructureTypeCommandBufferAllocateInfo-40]
	_ = x[StructureTypeCommandBufferInheritanceInfo-41]
	_ = x[StructureTypeCommandBufferBeginInfo-42]
	_ = x[StructureTypeRenderPassBeginInfo-43]
	_ = x[StructureTypeBufferMemoryBarrier-44]
	_ = x[StructureTypeImageMemoryBarrier-45]
	_ = x[StructureTypeMemoryBarrier-46]
	_ = x[StructureTypeLoaderInstanceCreateInfo-47]
	_ = x[StructureTypeLoaderDeviceCreateInfo-48]
	_ = x[StructureTypePhysicalDeviceGroupProperties-1000070000]
}

const (
	_StructureType_name_0 = "StructureTypeApplicationInfoStructureTypeInstanceCreateInfoStructureTypeDeviceQueueCreateInfoStructureTypeDeviceCreateInfoStructureTypeSubmitInfoStructureTypeMemoryAllocateInfoStructureTypeMappedMemoryRangeStructureTypeBindSparseInfoStructureTypeFenceCreateInfoStructureTypeSemaphoreCreateInfoStructureTypeEventCreateInfoStructureTypeQueryPoolCreateInfoStructureTypeBufferCreateInfoStructureTypeBufferViewCreateInfoStructureTypeImageCreateInfoStructureTypeImageViewCreateInfoStructureTypeShaderModuleCreateInfoStructureTypePipelineCacheCreateInfoStructureTypePipelineShaderStageCreateInfoStructureTypePipelineVertexInputStateCreateInfoStructureTypePipelineInputAssemblyStateCreateInfoStructureTypePipelineTessellationStateCreateInfoStructureTypePipelineViewportStateCreateInfoStructureTypePipelineRasterizationStateCreateInfoStructureTypePipelineMultisampleStateCreateInfoStructureTypePipelineDepthStencilStateCreateInfoStructureTypePipelineColorBlendStateCreateInfoStructureTypePipelineDynamicStateCreateInfoStructureTypeGraphicsPipelineCreateInfoStructureTypeComputePipelineCreateInfoStructureTypePipelineLayoutCreateInfoStructureTypeSamplerCreateInfoStructureTypeDescriptorSetLayoutCreateInfoStructureTypeDescriptorPoolCreateInfoStructureTypeDescriptorSetAllocateInfoStructureTypeWriteDescriptorSetStructureTypeCopyDescriptorSetStructureTypeFramebufferCreateInfoStructureTypeRenderPassCreateInfoStructureTypeCommandPoolCreateInfoStructureTypeCommandBufferAllocateInfoStructureTypeCommandBufferInheritanceInfoStructureTypeCommandBufferBeginInfoStructureTypeRenderPassBeginInfoStructureTypeBufferMemoryBarrierStructureTypeImageMemoryBarrierStructureTypeMemoryBarrierStructureTypeLoaderInstanceCreateInfoStructureTypeLoaderDeviceCreateInfo"
	_StructureType_name_1 = "StructureTypePhysicalDeviceGroupProperties"
)

var (
	_StructureType_index_0 = [...]uint16{0, 28, 59, 93, 122, 145, 176, 206, 233, 261, 293, 321, 353, 382, 415, 443, 475, 510, 546, 588, 635, 684, 732, 776, 825, 872, 920, 966, 1009, 1048, 1086, 1123, 1153, 1195, 1232, 1270, 1301, 1331, 1365, 1398, 1432, 1470, 1511, 1546, 1578, 1610, 1641, 1667, 1704, 1739}
)

func (i StructureType) String() string {
	switch {
	case 0 <= i && i <= 48:
		return _StructureType_name_0[_StructureType_index_0[i]:_StructureType_index_0[i+1]]
	case i == 1000070000:
		return _StructureType_name_1
	default:
		return "StructureType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
